### ISSUE TITLE
[Feature] :+1: 几点建议

### ISSUE THREAD

**Issue by Free-Aaron-Li** [Pylogmon/pot#11]
**需求描述**
1、窗口打开光标已经聚焦
2、动态翻译
3、支持单词详细描述（及词库功能）
**应用场景**
1、当使用Ctrl+D/Ctrl+Shift+D打开pot界面时，能够直接输入需要翻译的内容，而不是需要使用光标点击一下。
2、希望能够支持动态翻译，或者支持使用快捷键（如Alt+Enter）一键翻译，提高翻译效率。

**Comment by Pylogmon** [comment]
请问是什么系统呢，动态翻译是什么意思，我不是很懂你的意思。

**Comment by Pylogmon** [comment]
Linux的话，Tauri在Gnome桌面上有点问题，现在还不确定是tauri的问题还是gnome的问题，无法获取窗口焦点，虽然文本框设置了聚焦，但是没有捕获窗口焦点还是没用，具体看这个[https://github.com/tauri-apps/tauri/issues/6310](https://github.com/tauri-apps/tauri/issues/6310)

**Comment by Pylogmon** [comment]
已经添加了回车键翻译

**Comment by Pylogmon** [comment]
关于词库，各个接口支持情况不一样，不太好支持，而且也不符合这个软件的定位，暂时不考虑支持。

**Comment by Free-Aaron-Li** [comment]
动态翻译指的是：

https://user-images.githubusercontent.com/95997167/224240871-3bf88385-6ec3-446d-b770-9b5c070e22ac.mp4

**Comment by Pylogmon** [comment]
对于使用key的软件，这样多吃发送请求，感觉会徒增话费，已经支持回车键翻译了，我觉得这也没必要了。

**Comment by Free-Aaron-Li** [comment]
我也是这样认为的，但是可以提供这样的需求。
比如：用户使用自己的API，可以为用户提供这样选择。
使得软件多样化。

----
当然，直接使用回车翻译也不错。

**Comment by Pylogmon** [comment]
嗯，好的，感谢反馈，都是很棒的建议👍
