### ISSUE TITLE
[Feature] 支持使用 API2D 的 key

### ISSUE THREAD

**Issue by numbbbbb** [Pylogmon/pot#13]
Hello，请问是否考虑在项目中支持 [API2D](https://api2d.com/) 的 key？

由于众所周知的原因 openai 的访问以及 key 申请对普通开发者来说难度越来越大，接口请求也已经被 ban，我们做了一个服务 API2D 来代理请求。和 openai 用法类似，用户注册之后可以拿到一个 key，填入各种应用去发起对 openai 的请求。

从实现上来说，就是允许用户在配置 openai key 的地方配置 API2D 的 key，然后识别到是 API2D 的 key 之后，把 openai 的请求发送到 API2D 服务器（`https://openai.api2d.net`）即可。请求格式和 openai 完全一致，只是做了代理。

如果能够支持 API2D 的 key，我们可以把项目和链接信息都加入到 API2D 的兼容应用页面，这样所有的用户都可以在这里看到。

<img width="1914" alt="CleanShot 2023-03-09 at 10 18 13@2x" src="https://user-images.githubusercontent.com/2572987/224086126-0518c4f9-0888-400a-9d62-be4ff2a77e79.png">

**Comment by Pylogmon** [comment]
应用是支持设置自定义域名的，应该可以直接用的，不需要判断。

**Comment by numbbbbb** [comment]
好的我试下，多谢！
