### ISSUE TITLE
几点新建议[Feature] 

### ISSUE THREAD

**Issue by cccpism** [Pylogmon/pot#15]
**需求描述**
1.开机自启动设置
2.划词自动弹窗（划词后出现mini菜单，鼠标触及即可展开翻译）
3.谷歌翻译考虑接入吗？

**Comment by Pylogmon** [comment]
1. 开机自启是可以自己手动设置的，不过后续也可以考虑在软件设置页加上这一功能。
2. 设计之初就有过这方面的考虑，由于要做跨平台，自动弹窗实际上并不好做，而且考虑到很多场景下划词是不需要翻译的，做了这个功能就还得有相应的设置软件黑名单的功能，不如快捷键按需调用灵活。
3. 谷歌翻译由于没有开放的api,目前还没有找到好的解决方案，如果有好的方案可以推荐。

**Comment by cccpism** [comment]
> 1. 开机自启是可以自己手动设置的，不过后续也可以考虑在软件设置页加上这一功能。
> 
> 2. 设计之初就有过这方面的考虑，由于要做跨平台，自动弹窗实际上并不好做，而且考虑到很多场景下划词是不需要翻译的，做了这个功能就还得有相应的设置软件黑名单的功能，不如快捷键按需调用灵活。
> 
> 3. 谷歌翻译由于没有开放的api,目前还没有找到好的解决方案，如果有好的方案可以推荐。

1的话毕竟还是要照顾下我们这种小白嘛，自己找教程设置还是有点麻烦的。233333
2的话以我个人来看作者可能多虑了，参照现在市面上的各家翻译软件，其实都是这样的，设置一个mini按钮，你要想翻译你就碰一下，你不想翻译就不管了，只是重要的是不要把原有的菜单给挤掉了或覆盖了就好了。
以上仅供作者参考

**Comment by Pylogmon** [comment]
其实就是水平有限🤣

**Comment by cccpism** [comment]
> 其实就是水平有限🤣

啊这，好吧....不过顺带再问一下，为什么我填了open ai的api，重启了，他报错，说不知道这样的主机，报错代码11001，这是为什么？

**Comment by Pylogmon** [comment]
截图看看呢

**Comment by Pylogmon** [comment]
看起来像是网络问题，openai的官方api已经被ban了，你网络环境正常吗

**Comment by cccpism** [comment]
![image](https://user-images.githubusercontent.com/93852710/224460043-4c3bacaa-9ba6-4419-a250-92f9b6f9654a.png)
全程科学上网

**Comment by Pylogmon** [comment]
我没法定位问题，其他翻译接口能用吗，只有openai的用不了还是都有这个报错，有道的接口能不能用？

**Comment by cccpism** [comment]
> 我没法定位问题，其他翻译接口能用吗，只有openai的用不了还是都有这个报错，有道的接口能不能用？

有道的能用，其他的没有申请，不过openai的自定义域名我没写，那个必填吗？

**Comment by Pylogmon** [comment]
失误了，咋编辑你的内容了哈哈哈

不填应该有默认值的呀，填api.openai.com

**Comment by cccpism** [comment]
> 失误了，咋编辑你的内容了哈哈哈
> 
> 
> 
> 不填应该有默认值的呀，填api.openai.com

问题解决了，就是没有自定义域名的问题👌😂😂😂

**Comment by Pylogmon** [comment]
> > 失误了，咋编辑你的内容了哈哈哈
> > 
> > 
> > 
> > 不填应该有默认值的呀，填api.openai.com
> 
> 问题解决了，就是没有自定义域名的问题👌😂😂😂

你应该是把默认设置给删了

**Comment by Pylogmon** [comment]
哦不对，是我的问题，马上修，感谢

**Comment by Pylogmon** [comment]
谷歌翻译已经支持 #19

这个issue应该可以关了

**Comment by cccpism** [comment]
> 谷歌翻译已经支持 #19
> 
> 这个issue应该可以关了

别急啊，我刚想到一个，能有自动更新吗？还有，能把皮肤设置成跟随系统吗？

**Comment by Pylogmon** [comment]
可以新开issue,一个问题一个issue,方便管理

**Comment by Pylogmon** [comment]
关于这些问题等你新开issue我再回答吧，方便别人搜索查阅
