### ISSUE TITLE
[Feature] 支持 MacOS 平台

### ISSUE THREAD

**Issue by mkdir700** [Pylogmon/pot#16]
**需求描述**
hello，我想问下目前是仅支持 Linux/Windows 平台吗，没有看到 MacOS 应用安装程序。

**Comment by Pylogmon** [comment]
mac后续会支持，暂时还没有支持

**Comment by mkdir700** [comment]
> mac后续会支持，暂时还没有支持

我可以尝试贡献代码和帮助测试，虽然在 rust 上我是个菜鸟 😄

**Comment by Pylogmon** [comment]
> > mac后续会支持，暂时还没有支持
> 
> 我可以尝试贡献代码和帮助测试，虽然在 rust 上我是个菜鸟 😄 

可以可以，我才是菜鸟，看代码就能看出来

**Comment by mkdir700** [comment]
https://github.com/Pylogmon/pot/blob/f2bc4f6975e0f4358ddf78086d8ba19d5ba37788/src-tauri/src/selection.rs#L13-L22

这个函数的功能是从剪切板获取最近一个的内容吧，会不会有什么歧义

**Comment by Pylogmon** [comment]
是获取当前鼠标选中的内容，windows下采用的获取方案是键盘模拟Ctrl+C之后读取剪切板，由于不同平台下获取方式不一样，比如Linux下就不是读取剪切板，但是又需要同样的函数名，所以叫`get_selection_text`

**Comment by Pylogmon** [comment]
要适配macos只需要做两件事：
1. 为macos实现一个`get_selection_text`函数。
2. 在`shortcut.rs`和`trayicon.rs`中的创建窗口步骤中不要加入`transparent(true)`
```
let window = tauri::WindowBuilder::new(
                handle,
                "translator",
                tauri::WindowUrl::App("index_translator.html".into()),
            )
            .inner_size(400.0, 500.0)
            .min_inner_size(400.0, 400.0)
            .always_on_top(true)
            .transparent(true)  <---在macos下编译时把这行删除，可以通过条件编译完成
            .decorations(false)
            .skip_taskbar(true)
            .center()
            .focused(true)
            .title("Translator")
            .build()
            .unwrap();
```

**Comment by mkdir700** [comment]
> 要适配macos只需要做两件事：
> 
> 1. 为macos实现一个`get_selection_text`函数。
> 2. 在`shortcut.rs`和`trayicon.rs`中的创建窗口步骤中不要加入`transparent(true)`
> 
> ```rust
> let window = tauri::WindowBuilder::new(
>                 handle,
>                 "translator",
>                 tauri::WindowUrl::App("index_translator.html".into()),
>             )
>             .inner_size(400.0, 500.0)
>             .min_inner_size(400.0, 400.0)
>             .always_on_top(true)
>             .transparent(true)  <---在macos下编译时把这行删除，可以通过条件编译完成
>             .decorations(false)
>             .skip_taskbar(true)
>             .center()
>             .focused(true)
>             .title("Translator")
>             .build()
>             .unwrap();
> ```

是的，`.transparent(true) ` 会编译报错。

我还没有找到关于 macos 复制选中内容的相关内容（可能是我搜索方式不对）

**Comment by Pylogmon** [comment]
建议不要去复制，Windows那么搞实属下下策，建议看看macos的系统API，是有获取选中文本的接口的。

**Comment by mkdir700** [comment]
> 建议不要去复制，Windows那么搞实属下下策，建议看看macos的系统API，是有获取选中文本的接口的。

嗯嗯，好的

**Comment by Pylogmon** [comment]
transparent是为了在Linux下实现窗口圆角，这个方法在macos下貌似是调用了什么私有接口，macos下窗口应该默认是有圆角的，所以通过条件编译在mac下不要编译这一步就行

**Comment by Pylogmon** [comment]
macos的编译问题我已经解决了，你只要实现get_selection_text就好

**Comment by mkdir700** [comment]
> macos的编译问题我已经解决了，你只要实现get_selection_text就好

nice！

**Comment by Pylogmon** [comment]
暂时用剪切板支持了
