### ISSUE TITLE
[BUG] 图标点击无反应

### ISSUE THREAD

**Issue by Lichenkass** [Pylogmon/pot#18]
**问题描述**
Dock栏应用图标右键点击后出现的翻译/设置/退出无法点击，只能通过系统监视器关闭应用
![BUG](https://user-images.githubusercontent.com/88034509/224466306-d1e1e609-c30a-4210-8f23-e86d899468fe.jpeg)

**复现步骤**
偶发，安装后出现

**环境**
 - 操作系统: Deepin 20.8
 - 窗口系统:DDE
 - 软件版本: POT_0.0.11

**补充信息**
暂无

**Comment by Pylogmon** [comment]
会不会是deepin的bug，据说QQ的托盘图标也有问题

**Comment by Lichenkass** [comment]
不太像，其他应用都可以正常使用，只有POT点不了，QQ只是下面的QQ图标会消失  可以使用快捷键呼出应用   
![QQ20230311-131912](https://user-images.githubusercontent.com/88034509/224466561-093beb77-399d-4fae-a09e-66b270ee779c.png)

**Comment by Pylogmon** [comment]
是通过deb包安装的吗，依赖装全没

**Comment by Lichenkass** [comment]
通过Deb包安装的，你们提供的包和我自己打得包都有出现，依赖没有问题

**Comment by Pylogmon** [comment]
https://user-images.githubusercontent.com/59004461/224472841-8a7c2294-830d-4411-b2fa-6596aaa550b2.mp4

我在20.8无法复现

**Comment by Lichenkass** [comment]
> 我在20.8无法复现

有空我试下怎么才能复线

**Comment by Lichenkass** [comment]
> 我在20.8无法复现
实测发现  ：
先用鼠标左键点击POT图标就会出现bug,先使用右键就不会出现
![截图_选择区域_20230312100045](https://user-images.githubusercontent.com/88034509/224520066-502d67d8-b5e6-41c4-9bba-f46f793e5719.png)
