### ISSUE TITLE
设置无法保存

### ISSUE THREAD

**Issue by ZIDOUZI** [Pylogmon/pot#20]
**问题描述**
无法修改翻译类型

**复现步骤**
安装后在设置修改默认接口, 改为谷歌翻译, 保存关闭窗口后仍使用有道翻译.

**环境**
 - 操作系统: Windows
 - 软件版本: 0.0.12

**补充信息**

**Comment by Pylogmon** [comment]
重启应用生效

**Comment by Pylogmon** [comment]
暂时设置没有热重载，后续会加

**Comment by Pylogmon** [comment]
问题已解决
