### ISSUE TITLE
关于一些常见的闪退原因

### ISSUE THREAD

**Issue by Pylogmon** [Pylogmon/pot#21]
# Linux
### 原因
系统的glibc或openssl版本过低，默认的deb包是在Ubuntu22.04上编译的，需要`glibc>=2.34`,`openssl=3.x`
### 解决方案
Release中另外提供了使用Debian10编译的deb包`pot_<version>_amd64_universal.deb`，需要`glibc=2.28`,`openssl=1.1`，请根据实际情况选择对应的包来安装。

# Windows
### 原因
软件被某些杀毒软件误报，作者目前遇到过两次，还不清楚具体的原因，看tauri的issue,也有遇到同样问题的人，但目前还没发现具体的原因。
### 解决方案
在杀毒软件中还原，并将软件加入白名单

**Comment by Entershifttab** [comment]
在杀毒软件中还原，并将软件加入白名单,还是有闪退的情况

**Comment by Pylogmon** [comment]
闪退之后exe文件在不在

**Comment by Entershifttab** [comment]
还在,启动后会在工具栏显示一下图标,鼠标移动过去就会消失了,任务管理器里也没有出现这个应用运行的痕迹

**Comment by Pylogmon** [comment]
那应该是第一次启动时写入了错误的配置，还没写完就让杀了，把配置文件删了试试

**Comment by Pylogmon** [comment]
配置文件路径 https://pot.pylogmon.cn/guide/config.html#%E8%AE%BE%E7%BD%AE%E6%97%A0%E6%95%88%E5%AF%BC%E8%87%B4%E8%BD%AF%E4%BB%B6%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5

**Comment by Entershifttab** [comment]
成功了,感谢作者 !!!
@Pylogmon

**Comment by gclm** [comment]
> 配置文件路径 https://pot.pylogmon.cn/guide/config.html#%E8%AE%BE%E7%BD%AE%E6%97%A0%E6%95%88%E5%AF%BC%E8%87%B4%E8%BD%AF%E4%BB%B6%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5

连接无法打开

**Comment by Pylogmon** [comment]
官网更新了，现在看

https://pot.pylogmon.cn/docs/tutorial/config#%E8%AE%BE%E7%BD%AE%E6%97%A0%E6%95%88%E5%AF%BC%E8%87%B4%E8%BD%AF%E4%BB%B6%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5
