### ISSUE TITLE
[BUG] 无法运行安装程序

### ISSUE THREAD

**Issue by zqguang3708** [Pylogmon/pot#22]
**问题描述**
双击安装程序，并没有进行安装，没有任何反应

**环境**
使用的程序为：pot_0.0.12_x64_en-US.msi
操作系统：Microsoft Windows 10 专业版

**Comment by Pylogmon** [comment]
有没有其他信息呢，我没办法复现，也没法确认问题

**Comment by zqguang3708** [comment]
> 有没有其他信息呢，我没办法复现，也没法确认问题

感谢开发者的回复！
我通过双击/右键-安装的方式安装，均未弹出对话框。
然后我视图获取msi安装过程中的日志，发现这种方法可以正常安装：
在命令提示符中：

> msiexec /i pot_0.0.12_x64_en-US.msi /log log.txt

目前尚未确定原因，但是问题已经解决。
再次感谢开发者。
