### ISSUE TITLE
[Feature] 开机启动，自动主题

### ISSUE THREAD

**Issue by cccpism** [Pylogmon/pot#23]
**需求描述**
- [x] 开机自启动
- [x] 界面跟随系统
翻译界面记住上次的位置
再补充一个，当我划词翻译并显示结果后，建议要么失焦即消失，要么就可以自动获取下次划词的内容，不然下次划词的时候我还要专门ctrl+d退出后再来来一遍，就很麻烦。

**Comment by Pylogmon** [comment]
翻译界面是在鼠标指针位置出现的，为什么要记住位置呢

**Comment by Pylogmon** [comment]
Linux下是可以在失去焦点的时候自动关闭的，但是Windows下拖动窗口就会失去焦点，暂时无法实现

**Comment by Pylogmon** [comment]
还有，新的问题请开新的issue，issue又不要钱，都写一个里边别人看不到，我也不一定看得到。

**Comment by cccpism** [comment]
> 翻译界面是在鼠标指针位置出现的，为什么要记住位置呢

因为文本的位置有些比较靠下或者比较偏的，鼠标划词后顺手就会ctrl+d，这样就会显示不全，不可能说划词后还专门把鼠标移一下，再快捷键，这就不方便啊。

**Comment by cccpism** [comment]
> 还有，新的问题请开新的issue，issue又不要钱，都写一个里边别人看不到，我也不一定看得到。

行，下次注意

**Comment by Pylogmon** [comment]
那个以后会做判断，限定范围，不会超出屏幕，如果记住位置的话，翻译上面的文字岂不是又到下面去了

**Comment by cccpism** [comment]
> 那个以后会做判断，限定范围，不会超出屏幕，如果记住位置的话，翻译上面的文字岂不是又到下面去了

也行，我主要是提一下想法，大佬有更好的想法当然最好啦

**Comment by Apiketheworld** [comment]
确实需要一个限定范围，翻译屏幕下方或者靠右的时候窗口会在屏幕外
