### ISSUE TITLE
[Feature] 设置热重载，按键设置快捷键

### ISSUE THREAD

**Issue by ugger0101** [Pylogmon/pot#25]
**问题描述**
1. 修改默认快捷键后复制翻译（tab+D），无法启动，找不到默认配置文件删除或修改为默认配置文件。
3. 彩云小译api（目前仅尝试过填写该api）设置后，点击保存设置后，关闭设置窗口，重新打开设置窗口，api输入框被清空了，大概率需要二次操作才能成功
- [x] 希望快捷键使用按键来设置，不应该让用户通过输入按键名称来设置。
- [x] 设置热重载 

**复现步骤**

**环境**
 - 操作系统: Windows
 - 窗口系统: [X11/Wayland] (Linux Only)
 - 软件版本: 0.13-0.14

**补充信息**

**Comment by Pylogmon** [comment]
#20

**Comment by Pylogmon** [comment]
1和3应该说的是同一个问题

**Comment by ugger0101** [comment]
删除了 C:\Users\usr\AppData\Local下的配置文件，并重新安装了，好像还是没解决，是配置文件找错了吗

**Comment by Pylogmon** [comment]
Local下应该没有配置文件，配置文件在Roaming下

**Comment by Pylogmon** [comment]
第一条是说设置为tab+D之后无法启动应用是吧，才看明白，因为tauri官网我也没找到可以设置的按键列表，只有两个例子，就先这么写了，这么自己输入确实是个问题，后续我再想办法改进吧。

**Comment by ugger0101** [comment]
> 第一条是说设置为tab+D之后无法启动应用是吧，才看明白，因为tauri官网我也没找到可以设置的按键列表，只有两个例子，就先这么写了，这么自己输入确实是个问题，后续我再想办法改进吧。

对的
![image](https://user-images.githubusercontent.com/21169694/224590443-f9b24ae2-e495-42a4-a538-5c52233b9a8f.png)
anz
这部分可以改成powertoys设置按键方式，暂停全局快捷键，然后读取按键。不过powertoys也不允许使用tab+D组合按键，我当时只是摸着顺手试试
