### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by joeyln** [Pylogmon/pot#26]
**问题描述**
![图片](https://user-images.githubusercontent.com/115394772/224594657-4132c805-3135-4350-978a-3621bf4c5fe1.png)

**复现步骤**
下载下来，输入了百度密钥，但是翻译出错，换其他翻译接口也一样。

**环境**
 - 操作系统: windows11
 - 窗口系统: 
 - 软件版本: pot: 0.0.14 tauri:1.2.4

**补充信息**
另外这个窗口还是有问题，应该限制窗口出现的位置不要超出屏幕，但是最好不要改变大小，否则跳出窗口，文本都是缩小状态我还得调整。
还有窗口默认pinned，能不能给个设置，我默认不想pinned。

**Comment by Pylogmon** [comment]
实际上现在的窗口大小才是正常的，之前的大窗口是因为设置错误，看我视频就可以看出来

**Comment by Pylogmon** [comment]
对于划词翻译的窗口，pin其实是没有作用的，在Linux下窗口失去焦点就会自动关闭，但是Windows下拖动窗口就会失去焦点，所以先把这个功能去了，暂时还没有找到解决方法。

**Comment by joeyln** [comment]
不好意思，这个bug好像跟我的代理有关，关了重启之后就好了。

**Comment by Pylogmon** [comment]
目前除了open ai的接口其他都无法走系统代理，后续会想办法解决，如果没有其他问题这个issue可以关了

**Comment by joeyln** [comment]
> 实际上现在的窗口大小才是正常的，之前的大窗口是因为设置错误，看我视频就可以看出来

![1678765141860](https://user-images.githubusercontent.com/115394772/224887207-fa4a50ab-281a-4db4-971b-c35d2e625121.jpg)
这是你所谓的正常窗口大小吗？ 你自己看看这正常吗，人家bob也是默认大窗口啊

**Comment by Pylogmon** [comment]
感谢反馈，我这边不是这样，
![image](https://user-images.githubusercontent.com/59004461/224928762-ff5b26bc-2383-44f0-97bb-557cefd50178.png)

应该是你屏幕分辨率太高了，后续会解决高分屏的问题。
