### ISSUE TITLE
[BUG] Windows 下无法启动

### ISSUE THREAD

**Issue by hiknn** [Pylogmon/pot#28]
锐龙芯片的win11，安装任何版本后打不开软件，右下角显示pot图标，但是把鼠标移动到图标位置，图标就消失了。

**Comment by gclm** [comment]
windows11 int 芯片同出现这个问题

**Comment by Pylogmon** [comment]
应该跟CPU型号没有关系，现在遇到的都是个别案例，可以加群讨论一下。

**Comment by Pylogmon** [comment]
已修复
