### ISSUE TITLE
[Feature]: 希望能设置双边目标语言，自动检测切换

### ISSUE THREAD

**Issue by W15br** [Pylogmon/pot#29]
### 需求描述

希望能设置目标语言：简体中文⇔英文，自动检测划词为其中一边，翻译成另一边

### 应用场景

希望能不用反复设置实现自由中译英、英译中

**Comment by Lichenkass** [comment]
感觉挺需要的

**Comment by Pylogmon** [comment]
源语言默认必须是auto,这样的话不是很好检测，不同的接口支持情况不一样，像有道翻译他只支持中英互译，他的接口就会去自动检测，其他的接口还没找到好的办法。
