### ISSUE TITLE
[Feature]: 新增多翻译源同时翻译以及新增deepl 翻译支持

### ISSUE THREAD

**Issue by gclm** [Pylogmon/pot#30]
### 需求描述

- [ ] 经过测试发现部分翻译源质量有限，多个来源同时翻译可以对照比对，翻译质量更高
- [x]  目前经过测试发现deepL翻译质量是最高的，希望新增支持，free api 地址：https://github.com/OwO-Network/DeepLX

### 应用场景

见上

**Comment by Pylogmon** [comment]
质量还能比openai高？😂
Deeplx已经有计划支持了，多个翻译源同时显示的话，目前还在考虑。
