### ISSUE TITLE
[Feature]: 焦点转移关闭窗口

### ISSUE THREAD

**Issue by Nolovenodie** [Pylogmon/pot#32]
### 需求描述

- [x] 类似Bob的操作体验，焦点转移到其余窗口 关闭翻译窗口
- [x] windows下的翻译窗口也许可以做的小一点，窗口较大，余白有点多
3. 快捷键翻译之后，需要关闭当前翻译窗口才能再次进行下次快捷键翻译，这个体验很不好，比如我现在 划词翻译 弹出窗口，然后再去 划词翻译 另外的内容，按下快捷键是直接关闭了上次的窗口，但是并没有翻译当前内容

### 应用场景

提高工作效率，减少多余操作

**Comment by Pylogmon** [comment]
这个功能其他平台是有，但是windows暂时没法实现，windows因为windows拖动窗口的时候会失去焦点导致窗口关闭，暂时还没找到解决办法。

**Comment by Nolovenodie** [comment]
还有就是esc快速关闭，第三个需求可以优化下~
