### ISSUE TITLE
[Feature]: 希望能将鼠标中键设置为快捷键。

### ISSUE THREAD

**Issue by cccpism** [Pylogmon/pot#35]
### 需求描述

希望能将鼠标中键设置为快捷键。

### 应用场景

我个人因为使用了挺多的软件，键盘上的快捷键占用较多，而且个人觉得在划词后直接通过鼠标中键等鼠标上的快捷键来实现即时翻译更方便点。

**Comment by Pylogmon** [comment]
如果是Windows，可以参考文档试试插件调用，其他平台后续也会支持插件调用。

**Comment by cccpism** [comment]
> 如果是Windows，可以参考文档试试插件调用，其他平台后续也会支持插件调用。

这，自己写插件的话，我对来说难度有点高，毕竟我不会……（疯狂流汗）

**Comment by cccpism** [comment]
> 如果是Windows，可以参考文档试试插件调用，其他平台后续也会支持插件调用。

所以有教程什么的吗，我后面自己慢慢摸索摸索

**Comment by Pylogmon** [comment]
文档给了呀

**Comment by cccpism** [comment]
> 文档给了呀

不是，我看到readme了，但里面涉及到自己写powershell code，我比较发愁那个玩意。

**Comment by Pylogmon** [comment]
内容我也给了呀
https://pot.pylogmon.cn/guide/config.html#%E6%8F%92%E4%BB%B6%E8%B0%83%E7%94%A8

**Comment by cccpism** [comment]
刚刚试了一下，snipdo还是无法做到为鼠标中键设置快捷键……

**Comment by Pylogmon** [comment]
都直接出现菜单了还要快捷键干什么😧

**Comment by cccpism** [comment]
确实确实，不过通过snipdo唤醒pot总是会和我另个一软件发生冲突，然后就是唤醒了那个软件，pot的窗口被关闭，不知道哪里有问题，我再看看

**Comment by Pylogmon** [comment]
插件调用的时候使用的是软件exe的绝对路径，期间并不会涉及快捷键之类的东西，按理说不应该和任何软件有冲突。

**Comment by cccpism** [comment]
我刚刚解决了这个问题，因为我把调用划词翻译的快捷键和另一个软件的设置为相同的了。但按你说的话，我通过snipdo调用也不应该出现这个问题啊

**Comment by Pylogmon** [comment]
你创建插件的时候写的内容是什么

**Comment by cccpism** [comment]
就是你给的那个D:\Softwares\pot\pot.exe popclip "$PLAIN_TEXT"。然后我把路径换成我的路径，就没啦
