### ISSUE TITLE
[BUG]: 腾讯翻译君填入秘钥后保存失效

### ISSUE THREAD

**Issue by Core5God** [Pylogmon/pot#38]
### 问题描述

秘钥无法保存，翻译无法使用

### 如何复现

填入-保存设置-关闭再打开-秘钥没有了

### 操作系统

Windows (Default)

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
是最新版本吗

**Comment by Core5God** [comment]
pot: 0.1.9 tauri:1.2.4

**Comment by Pylogmon** [comment]
好的，我查一下问题，感谢反馈，修复之前可以先使用0.1.8版本。

**Comment by Pylogmon** [comment]
已修复，下个版本即可解决。
