### ISSUE TITLE
[Feature]: <关于在PDF中选中段落的问题>

### ISSUE THREAD

**Issue by NTDXYG** [Pylogmon/pot#39]
### 需求描述

比如在浏览器中打开论文的pdf文件时，需要划词翻译，这个时候选中的段落是这样的
`Over the past decade, deep learning (DL) has made lots of progress and has achieved state-ofthe-art (SOTA) performance for many applications across domains, e.g., image processing, speech
recognition, natural language processing (NLP), medical diagnosis.`
而我希望得到的段落应该是没有回车的，即
`Over the past decade, deep learning (DL) has made lots of progress and has achieved state-of-the-art (SOTA) performance for many applications across domains, e.g., image processing, speech recognition, natural language processing (NLP), medical diagnosis.`
我大致看了一下源码，应该是在‘src/windows/translator/components/SourceArea/index.jsx’的line 20进行改进和优化。

### 应用场景

经常会看论文或者pdf文献，因此我觉得这是一个比较重要的痛点。

**Comment by Pylogmon** [comment]
我理解的没错的话，这应该是PDF的排版问题，一般复杂点的PDF选中段落复制之后都会有这个问题，如果说我手动把换行去了的话，那是不是选中其他正常有换行的文本的时候又会显示不正常呢？

**Comment by NTDXYG** [comment]
是的，我觉得有道翻译在这方面处理得很好。。但我也不知道他们是怎么处理这个问题的，一个可能的方案是单独加个针对pdf的划词翻译快捷键？虽然这看上去很蠢，但我觉得很实用😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月5日(周三) 晚上10:21
收件人: ***@***.***&gt;;
抄送: "Guang ***@***.******@***.***&gt;;
主题: Re: [Pylogmon/pot] [Feature]: <关于在PDF中选中段落的问题&gt; (Issue #39)




 
我理解的没错的话，这应该是PDF的排版问题，一般复杂点的PDF选中段落复制之后都会有这个问题，如果说我手动把换行去了的话，那是不是选中其他正常有换行的文本的时候又会显示不正常呢？

**Comment by Pylogmon** [comment]
刚刚试了一下，随即在那段文本中加几个换行，用OpenAI来翻译的话，就算我不去处理换行，他的翻译结果也会处理的很不错，可以先试试用OpenAI的接口。

**Comment by Pylogmon** [comment]
想了一下，不一定要加一个快捷键，在翻译面板上加一个一键去除所有换行的按钮或许不错。

**Comment by NTDXYG** [comment]
我觉得可以哦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月5日(周三) 晚上11:42
收件人: ***@***.***&gt;;
抄送: "Guang ***@***.******@***.***&gt;;
主题: Re: [Pylogmon/pot] [Feature]: <关于在PDF中选中段落的问题&gt; (Issue #39)




 
想了一下，不一定要加一个快捷键，在翻译面板上加一个一键去除所有换行的按钮或许不错。

**Comment by Pylogmon** [comment]
![图片](https://user-images.githubusercontent.com/59004461/230136077-38cc24cb-fb2d-43ae-a7d7-a62ad70a8c5b.png)
