### ISSUE TITLE
[Feature]: <自动去除换行符>

### ISSUE THREAD

**Issue by DONTKK** [Pylogmon/pot#40]
### 需求描述

文献阅读时，pdf划词翻译时会多出来一些换行符，希望划词翻译能够附加一个可以自动去除换行符的功能

### 应用场景

文献阅读

**Comment by Pylogmon** [comment]
已经加了的 #39 下个版本就可以用了，稍等我发一版吧😂

**Comment by Pylogmon** [comment]
[0.1.13](https://github.com/Pylogmon/pot/releases/tag/0.1.13) 已经发布
