### ISSUE TITLE
[Feature]: 希望增加复制原文/复制译文的快捷键

### ISSUE THREAD

**Issue by laoliloal** [Pylogmon/pot#41]
### 需求描述

当deepL给出翻译结果后，希望能快速复制译文以及复制原文。

### 应用场景

读文献写笔记，希望写成一篇一段中文一段英文的对照形式。通过快捷键可以实现无感后台翻译。

### 参考资料

可参考[CopyTranslator](https://github.com/CopyTranslator/CopyTranslator)，其实现了此功能
（顺带吐槽一下，copytranslator之前deepl用的蛮好的，最近突然不好使了，也没有修）

**Comment by Pylogmon** [comment]
看了一下，很不错的软件。

你的意思是说在翻译面板出现后，添加一个全局的快捷键来复制原文或者译文吗？

我在想有没有更好的交互方式能够跟目前的交互方式相匹配，以现在的交互方式来看，翻译之后，点击复制译文，然后去粘贴，这时候翻译窗口因为失去焦点已经自动关闭了，有复制原文的快捷键也没有意义了。

或许添加一个设置项，翻译后自动复制原文和译文也不错，你觉得呢？如果你有更好的想法，欢迎留言🙂。

**Comment by Pylogmon** [comment]
![image](https://user-images.githubusercontent.com/59004461/230820237-a8d43793-78c2-43d1-994d-2d1a09d75edf.png)

这样应该不错，感谢建议😄

**Comment by laoliloal** [comment]
> 

这样很不错！感谢作者！

**Comment by Pylogmon** [comment]
可以去actions页面下载自动构建版本体验 https://github.com/Pylogmon/pot/actions/runs/4654232406

**Comment by laoliloal** [comment]
测试了，很好的功能，点赞！感谢作者大大，辛苦了！
但我遇到一个问题，有时选中一段文字→CTRL+D，弹出的翻译窗口没有翻译这段文字，就是翻译窗口上半部分没有文字。
一般来说，pot打开后，选中一段文字→CTRL+D→点击翻译框外→选中另一段文字→CTRL+D，就会出现这种问题。系统是win10家庭普通版。
如果作者方便的话可以排查下，感谢！

**Comment by Pylogmon** [comment]
快捷键调用是模拟CtrlC来复制的，有时候就是不稳定，我也在想办法解决，可以先试试插件调用。

**Comment by Pylogmon** [comment]
试着修了一下，自动构建完成后麻烦帮忙测试一下，大概需要编译十三分钟左右。

https://github.com/Pylogmon/pot/actions/runs/4663976204
