### ISSUE TITLE
[bug]：划词翻译无法获取Linux WPS pdf中的文字

### ISSUE THREAD

**Issue by ccloud0525** [Pylogmon/pot#42]
### 问题描述

在Deepin20.9系统下，在划取pdf中的文字后使用划词翻译功能，pot并不能获取到文本

### 如何复现

Deepin20.9下，用WPS打开任意pdf文献，划词，使用快捷键触发划词翻译，发现原文一栏无文本

### 操作系统

Linux

### 操作系统版本

Deepin20.9

### 窗口系统(Linux Only)

None

### 软件版本

pot: 0.1.15 tauri:1.2.4

**Comment by Pylogmon** [comment]
已知问题，应该是wps的问题，浏览器打开pdf是可以正常取词的，这个目前还没有办法解决。

**Comment by ccloud0525** [comment]
> 已知问题，应该是wps的问题，浏览器打开pdf是可以正常取词的，这个目前还没有办法解决。

收到，希望作者越做越好！

**Comment by lingchuanbo** [comment]
百分浏览器也是一样 无法获取文字

**Comment by Pylogmon** [comment]
> 百分浏览器也是一样 无法获取文字

是百分浏览器中无法获取文字还是说用百分浏览器打开PDF无法获取文字
有没有测试过其他浏览器呢

**Comment by Pylogmon** [comment]
已经尝试修复，如果仍然存在问题，请重新打开此issue

**Comment by ACGNworld** [comment]
> 已经尝试修复，如果仍然存在问题，请重新打开此issue

还是会有问题，当前最新版pot，12.0.1.17885的wps，pdf取词取不到
