### ISSUE TITLE
[Feature]: 交换翻译语言，或自动翻译到目标语言

### ISSUE THREAD

**Issue by xuestrange** [Pylogmon/pot#44]
### 需求描述

Pot的默认翻译设置为从自动检测翻译为简体中文，能不能改进为“其他语言自动翻译为中文，遇到中文自动翻译为其他语言，例如英文”

### 应用场景

常常要进行中英文切换，因为不仅仅要读论文，写论文的时候需要把中文翻译成英文。

**Comment by Pylogmon** [comment]
那具体是翻译成英文还是中文呢，还得加个设置项吗，这样还得检测语种，语种检测不一定准确的，我觉得加个记住目标语言语言的功能效果应该也不错。

**Comment by xuestrange** [comment]
建议如下

下方图片为当前版本的示意，将>>改为一个按钮，按一下就会调整为反方向，例如>>按一下就变成<<这就表示相反方向翻译了，也不需要检测语种。（这样做的原因是，多数情境下都是两种语言的相互翻译）
![](https://raw.githubusercontent.com/xuestrange/picGoUploader/main/img/202304231544487.png)

**Comment by Pylogmon** [comment]
翻译接口请求的时候要求传入源语言和目标语言，源语言可以设置为auto人家自动检测，这样直接交换之后，目标语言变成了自动检测，这没法翻译呀。
