### ISSUE TITLE
[Feature]: 鼠标点击其他位置，自动隐藏翻译界面

### ISSUE THREAD

**Issue by xuestrange** [Pylogmon/pot#45]
### 需求描述

在按了快捷键后，会弹出翻译截面，但是翻译界面是以固定在其他窗口的最前面的形式出现的(x11)，希望取消这个默认设置，这样我就可以点击其他位置，自动隐藏翻译窗口了。如果确实需要固定在最前面，这个可以由用户进行选择啊。

### 应用场景

读论文的时候，每查一次都得手动关闭翻译截面。

**Comment by Pylogmon** [comment]
现在就是这样的，失去焦点的时候会自动关闭窗口，我猜你是gnome桌面吧，我现在已知有问题的就只有gnome桌面，Tauri在gnome桌面下无法捕获焦点，这是gnome的问题，我没有办法。

**Comment by Pylogmon** [comment]
刚刚发现KDE桌面也有问题，他只有在桌面上没有任何窗口有焦点的时候是正常的，一旦焦点在其他窗口上，这时候划词翻译就没法捕获焦点了。

**Comment by Pylogmon** [comment]
如果你是KDE用户的话，在系统设置中在窗口管理中关闭【阻止焦点抢占】就可以正常使用了
![image](https://user-images.githubusercontent.com/59004461/233794387-b16a6df1-012b-4cb4-aae3-e0ccb288406c.png)

**Comment by xuestrange** [comment]
好的，谢谢
