### ISSUE TITLE
[BUG]: 黑暗主题下，弹出窗口会先闪白一下

### ISSUE THREAD

**Issue by o000u** [Pylogmon/pot#46]
### 问题描述

如题，在黑暗主题下，每次呼出翻译窗口时，都会先闪现白色窗口再变黑，晚上关灯搞机的时候，经常被闪瞎，哈哈，，，
希望作者有空能跟进下这个问题，看能否解决。
感谢作者的卓越付出，真的很棒的软件！
希望越做越好！

### 如何复现

在黑暗主题模式下，激活Pot翻译窗口

### 操作系统

Windows (Default)

### 操作系统版本

Windows 11 22H2 22624.1610 专业版

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
我这边同样的win11没有这个问题，可以录个视频吗？

**Comment by Pylogmon** [comment]
好像是有点问题，我想办法修一下。

**Comment by o000u** [comment]
> 好像是有点问题，我想办法修一下。

嗯，辛苦作者!

**Comment by Pylogmon** [comment]
看起来是Windows webview的问题，我没办法修😰

**Comment by Pylogmon** [comment]
我试着修了一下，除了窗口出现更加平滑了，没有任何变化，这个问题应该就是webview的问题，我这边修不了，就算是我等到页面加载完成之后再显示窗口，也是会有那一下白的。

**Comment by o000u** [comment]
> 我试着修了一下，除了窗口出现更加平滑了，没有任何变化，这个问题应该就是webview的问题，我这边修不了，就算是我等到页面加载完成之后再显示窗口，也是会有那一下白的。

啊～～～So sad！。。。本来也想着应该是webview的锅，不过因为看到另一款同类翻译软件，应该也是用的webview，但就不会有这个问题，所以才过来反馈下看能否修。

对了，这款软件叫TTime，Git里也能搜到

**Comment by Pylogmon** [comment]
他没有开源，但是我看他应该是用的是electron，electron用的不是系统的webview，自带一个Chrome，就导致软件体积很大。

**Comment by o000u** [comment]
> 他没有开源，但是我看他应该是用的是electron，electron用的不是系统的webview，自带一个Chrome，就导致软件体积很大，但是效果很好。

哦哦，原来如此～～～难怪了

——看来，得等巨硬修了（相当于无解T_T）？

**Comment by Pylogmon** [comment]
具体是谁的锅我现在也不好说，我去tauri仓库提个issue问问看

**Comment by o000u** [comment]
> 具体是谁的锅我现在也不好说，我去tauri仓库提个issue问问看

嗯嗯，辛苦了～～～

**Comment by Pylogmon** [comment]
我发现设置窗口打开的情况下去划词翻译不会有任何闪烁，所以我用投机取巧的办法把这问题解决了，启动时创建一个无用的窗口，然后把这个窗口最小化到后台，现在就没有闪烁啦😄

**Comment by Pylogmon** [comment]
测试没有问题的话这个issue就可以关了

**Comment by o000u** [comment]
> 我发现设置窗口打开的情况下去划词翻译不会有任何闪烁，所以我用投机取巧的办法把这问题解决了，启动时创建一个无用的窗口，然后把这个窗口最小化到后台，现在就没有闪烁啦😄

WOW～～～佩服！！总觉得会带来惊喜，半夜想起来就来瞧一瞧，果真！！你太帅了大侠，这就去试试～～～

**Comment by o000u** [comment]
> 测试没有问题的话这个issue就可以关了

刚测试了，已完美解决[撒花]~~~
大侠威武！
可以关了^_^
