### ISSUE TITLE
请问有没有其他的在win上直接划词翻译的方法

### ISSUE THREAD

**Issue by lhj5426** [Pylogmon/pot#47]
### 需求描述

首先感谢 开发这个软件可以白嫖deepl而且速度很快 
就是从生理上 讨厌 win  的商店 非EXE 安装的 SnipDo 这玩意 

### 应用场景

生理上产生厌恶  有过痛苦的回忆 不想在弄了
https://github.com/poochie89/SnipDo-Extensions/issues/10 

### 参考资料

![image](https://user-images.githubusercontent.com/30548000/233832048-feff1160-cd78-4f28-a20f-fe25c2363cf8.png)
可不可以弄个像 QTranslate 这样的软件自带的划词功能？

**Comment by Pylogmon** [comment]
因为软件要考虑到跨平台，所以这个功能实现起来比较困难，而且各个平台有现成的类似的软件，人家专门做这个功能肯定比我要做的完善，所以直接以插件的形式支持这一功能体验是最好的，如果你不喜欢说实话我也不是很喜欢SnipDo，但是在Win下找了很久只有这一款软件能完美的符合需求，如果你有其他类似的软件推荐，可以告诉我我来适配，至于软件自身我是不打算实现这个功能的。

**Comment by lhj5426** [comment]
> 因为软件要考虑到跨平台，所以这个功能实现起来比较困难，而且各个平台有现成的类似的软件，人家专门做这个功能肯定比我要做的完善，所以直接以插件的形式支持这一功能_体验_是最好的，我在Win下找了很久只有这一款软件能完美的符合需求，如果你有其他类似的软件推荐，可以告诉我我来适配，至于软件自身我是不打算实现这个功能的。

行吧
