### ISSUE TITLE
[BUG]: openai自定义域名 返回结果错误

### ISSUE THREAD

**Issue by yedielnthabit** [Pylogmon/pot#50]
### 问题描述

在未设置自定义域名的情况下调用正常，设置自定义域名后返回结果异常 。已通过VScode REST插件验证域名没有问题
![屏幕截图 2023-04-25 190832](https://user-images.githubusercontent.com/120004270/234259485-ae89d737-666b-402d-9485-f7d8388f20fd.png)

### 如何复现

自定义域名后即可看到

### 操作系统

Windows (Default)

### 操作系统版本

windows11

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
按道理说，代理网站如果做的完全没问题的话，官方请求不会出错走你的代理也不会出错，因为只是做一个转发，一样的问题我也遇到过，大概率是你的反代做的不完善，可以看看我文档里写的那个项目，我用那个项目的代码再cloudflare部署反代测试是没有问题的。

**Comment by Pylogmon** [comment]
https://github.com/x-dr/chatgptProxyAPI

**Comment by yedielnthabit** [comment]
> 按道理说，代理网站如果做的完全没问题的话，官方请求不会出错走你的代理也不会出错，因为只是做一个转发，一样的问题我也遇到过，大概率是你的反代做的不完善，可以看看我文档里写的那个项目，我用那个项目的代码再cloudflare部署反代测试是没有问题的。

**Comment by yedielnthabit** [comment]
> https://github.com/x-dr/chatgptProxyAPI

我就是按照cloudflare来部署的反代 我再补充几张截图 分别是我用pot 与 vscode rest插件测试的结果 没用反代的情况下我关闭了代理 反之开启了代理
![屏幕截图 2023-04-25 192647](https://user-images.githubusercontent.com/120004270/234263459-20e3ad17-4c81-476b-bee7-43dfb2ea8621.png)
![屏幕截图 2023-04-25 192800](https://user-images.githubusercontent.com/120004270/234263471-deaa077e-d7db-40a2-b2e0-377018d60aad.png)
![Upload
![屏幕截图 2023-04-25 192921](https://user-images.githubusercontent.com/120004270/234263493-27d3ce54-d914-40d9-8b16-cc74a5e73871.png)
ing 屏幕截图 2023-04-25 192848.png…]()

**Comment by Pylogmon** [comment]
确定是用的这个项目吗，我之前用过其他人提供的方案会出现这个问题，用了这个项目就没问题了。

**Comment by Pylogmon** [comment]
我很清楚问题出在哪，因为一般来说请求体的body是用的json，我把json转为了字符串直接发送的，官方接口是支持这样的，但是一些不完善的反代不支持这样

**Comment by yedielnthabit** [comment]
> 我很清楚问题出在哪，因为一般来说请求体的body是用的json，我把json转为了字符串直接发送的，官方接口是支持这样的，但是一些不完善的反代不支持这样

我再看看反代的代码 我不能十分肯定是否就是这个项目 我只能确定是在你项目openai api 部署那里推荐的反代项目

**Comment by Pylogmon** [comment]
至于为什么这么做，因为我要实现软件级别的代理，所以不能直接在前端发请求，必须通过后端rust来发送，但是rust的reqwest发送json格式的body的时候老是出错，我还没找到原因，所以就统一都用字符串格式发送了，等我把这个问题解决了之后应该这种不完善的反代也就没问题了。

**Comment by Pylogmon** [comment]
> 我再看看反代的代码 我不能十分肯定是否就是这个项目 我只能确定是在你项目openai api 部署那里推荐的反代项目

文档里面改过一次，就是在我发现问题的时候，之前给的链接是一个项目的discussion，那个不完善。

**Comment by yedielnthabit** [comment]
> > 我再看看反代的代码 我不能十分肯定是否就是这个项目 我只能确定是在你项目openai api 部署那里推荐的反代项目
> 
> 文档里面改过一次，就是在我发现问题的时候，之前给的链接是一个项目的discussion，那个不完善。

确实是反代的问题 应用你给出的https://github.com/x-dr/chatgptProxyAPI 这个就可以了 非常感谢你的及时回复
