### ISSUE TITLE
[Feature]: Windows最小化后，点击弹出窗口

### ISSUE THREAD

**Issue by xuestrange** [Pylogmon/pot#51]
### 需求描述

Windows下最小化窗口后，点击图标可以弹出窗口。
<img src="https://raw.githubusercontent.com/xuestrange/picGoUploader/main/img/20230428135753.png">

### 应用场景

想输入翻译，而不是划词翻译

**Comment by Pylogmon** [comment]
输入翻译不也有快捷键吗🧐

**Comment by xuestrange** [comment]
这个，点击更方便一点吧，不需要记忆快捷键。

**Comment by Pylogmon** [comment]
![image](https://user-images.githubusercontent.com/59004461/235098344-bf5683d8-b2bb-4c8d-b672-552f6a42a544.png)

**Comment by xuestrange** [comment]
感谢:smile:
