### ISSUE TITLE
[BUG]: 朗读速度过快、无法实现中文朗读

### ISSUE THREAD

**Issue by Free-Aaron-Li** [Pylogmon/pot#53]
### 问题描述

- 如题，无论是待翻译文本还是翻译生成文本朗读的速度都过快，建议将其标明为重点解决bug，建议设置多级朗读速度，默认速度为1。
- 无法实现中文朗读（准确说是朗读中文朗读出来是无法理解的“单词”，使用的是默认翻译接口DeepL），我认为这个bug也较为严重。虽然在大多数情况下并不需要朗读中文，但既然存在朗读中文功能那么就应该保证其基本实现。

### 如何复现

- 输入待翻译文本，点击朗读按钮即可实现
- [测试视频](https://user-images.githubusercontent.com/95997167/235474267-715e14e1-aec5-48ee-b5c9-82feded5b072.mp4)

### 操作系统

Linux

### 操作系统版本

- Deepin20.9
- Linux 5.18.17-amd64-desktop-community-hwe #20.01.00.08 SMP PREEMPT_DYNAMIC Fri Dec 30 10:04:38 CST 2022 x86_64 GNU/Linux

### 窗口系统(Linux Only)

X11

### 软件版本

0.1.19

**Comment by Pylogmon** [comment]
这个问题我也发现了，排查之后发现目前使用的TTS方案实际上只支持英文，其他语言确实是乱讲的，我也在想办法使用其他方案来替代目前的方案，但还没有好的思路。
