### ISSUE TITLE
[BUG]: 客户端更新功能失效

### ISSUE THREAD

**Issue by mrzeuscn** [Pylogmon/pot#55]
### 问题描述

**更新按钮失效**
<img src="https://user-images.githubusercontent.com/7010266/235823027-d7c24ebe-b019-45c3-bb24-3a6ec908aa49.png" width = "50%">

### 如何复现

直接点击更新

### 操作系统

Windows (Default)

### 操作系统版本

Windows 11 专业版 22H2 22621.1635

### 软件版本

pot: 0.1.15 tauri:1.2.4

**Comment by Pylogmon** [comment]
一直也没有更新功能啊，只有检查更新。
如果你是说检查更新没有反应的话，因为检查更新需要githubAPI，因为网络原因这个是有概率获取失败的。

**Comment by mrzeuscn** [comment]
> 

明白了，是我理解错了。
