### ISSUE TITLE
[Feature]: 快捷键增加对F1-F12的支持

### ISSUE THREAD

**Issue by mrzeuscn** [Pylogmon/pot#56]
### 需求描述

希望快捷键支持 F1 - F12

### 应用场景

使用习惯

**Comment by Pylogmon** [comment]
OK,下个版本就可以使用了，你直接改配置文件也是可以使用的。

**Comment by mrzeuscn** [comment]
配置文件内容更改后，重启软件，又变回去了。
`shortcut_translate = "F9"`
`shortcut_persistent = "F10"`

**Comment by mrzeuscn** [comment]
> 
是我没保存，已经可以了。
