### ISSUE TITLE
优化建议：mac 菜单栏点击跳出设置不是翻译窗口优化

### ISSUE THREAD

**Issue by happykkAi** [Pylogmon/pot#57]
### 需求描述

用户使用习惯而言：点击菜单图标应该跳窗翻译窗口而不是设置，设置可以在双击后显示设置

问题：请问谷歌翻译：是否需要我们填写 eg：translate.google.com
<img width="598" alt="截屏2023-05-03 14 50 41" src="https://user-images.githubusercontent.com/92377310/235848859-adc5514b-866f-429e-9049-4f3417e9d21a.png">

### 应用场景

个人使用感受：我非常喜欢这个软件，体验了很多软件 包括easydict 和Bob，但是你们接入popclip后使用效率提高很多，但是在需要中文翻译成英文的时候，我们会自然点击图标希望跳出翻译窗口而不是设置。

**Comment by Pylogmon** [comment]
这个是有提供设置选项的
![image](https://user-images.githubusercontent.com/59004461/235852109-44161a88-b976-4c02-8243-0ae803c4542e.png)

**Comment by Pylogmon** [comment]
请问在Mac下不使用Popclip的情况下快捷键划词翻译可以使用吗，我没有Mac设备来测试，不知道这个问题修好没有。

**Comment by Pylogmon** [comment]
> 问题：请问谷歌翻译：是否需要我们填写 eg：translate.google.com

谷歌翻译的这一设置项是为了解决谷歌翻译在国内无法使用的问题，如果你有代理可以解决网络问题那就不需要填写，默认请求translate.google.com，如果不想使用代理，也可以在这里设置谷歌镜像站的地址。

**Comment by Pylogmon** [comment]
快捷键注册失败点击确认的时候会有提醒的，我的意思是说，能不能获取到选中的内容

**Comment by Pylogmon** [comment]
好吧，那就是没修好，感谢反馈，好用记得点个star哦
