### ISSUE TITLE
[Feature]: 参考百度翻译桌面端的，更快更简略的划译功能

### ISSUE THREAD

**Issue by Geopanret** [Pylogmon/pot#58]
### 需求描述

1. 百度翻译划译窗口更小，免除原文以及语言设置
2. 划译免去按下快捷键，即划即译

### 应用场景

玩文字类游戏，需要频繁、长短不一、响应迅速，且占用屏幕空间小的划译

### 参考资料

百度划译结果截图
![image](https://user-images.githubusercontent.com/88887974/236095822-9055b501-2aae-4b61-9e56-5861628cad7e.png)

**Comment by Geopanret** [comment]
pot的赛道在于能够自定义接口，而接口决定了响应速度和准确性
之所以不用百度翻译是因为其长文的翻译质量差强人意，而DeepL免费用户有1000字符限制
向开源作者致敬

**Comment by Pylogmon** [comment]
有没有设置插件调用？相对来说方便一些。

**Comment by Geopanret** [comment]
值得一提的是，百度翻译在划选动作后自动输入ctrl+c，而且对所有划选动作生效，会引发意外的划译和污染剪贴溥

也许可以设置仅对特定窗口开启划译的功能……？

插件调用是什么x

**Comment by Pylogmon** [comment]
pot的取词并不会污染剪切板，插件调用参考readme的展示，具体配置方法见官网

https://pot.pylogmon.cn/guide/config.html#%E6%8F%92%E4%BB%B6%E8%B0%83%E7%94%A8

**Comment by Geopanret** [comment]
了解了，这免去输入快捷键，但我贪婪地许愿能再免去鼠标点击x

是否考虑开发简略模式？例如划译模式下仅显示译文和重要按钮等等

**Comment by Pylogmon** [comment]
就像你说的那样，这一功能极易误触，支持之后就得花费大量心血完善白名单机制，所以我不打算支持，更何况我需要考虑跨平台支持，这样一来软件复杂度会大幅增加，我精力有限维护不了。
