### ISSUE TITLE
[BUG]: 状态栏图标点击延迟设定

### ISSUE THREAD

**Issue by xuestrange** [Pylogmon/pot#61]
### 问题描述

点击状态栏图标后，按道理讲会弹出界面。
然而我常常会多点了（点击两次），导致界面反而不出现

### 如何复现

鼠标在状态栏上点击Pot图标两次

### 操作系统

Windows (Default)

### 操作系统版本

Windows 10

### 窗口系统(Linux Only)

None

### 软件版本

0.2.4

### 补充信息

希望能设计一种防呆设计，点击一次两次都会出来，可以通过延迟实现（maybe）

**Comment by Pylogmon** [comment]
没能复现，我双击照样能启动

**Comment by Pylogmon** [comment]
你启动的是翻译窗口是吧，翻译窗口现有的逻辑是有有窗口实例存在的时候再次调用会关闭这个窗口，按两次快捷键也是这个效果，这个没法搞防呆。

**Comment by Pylogmon** [comment]
修了
