### ISSUE TITLE
[Feature]: Linux适配咨询

### ISSUE THREAD

**Issue by xuestrange** [Pylogmon/pot#62]
### 需求描述

请问目前Pot在哪个Linux发行版和桌面环境下适配比较好呢？
还有有无PDF阅读器（Linux）推荐啊？

### 应用场景

Linux发行版太多了，目前我在Manjaro Gnome上的使用体验并不太好

**Comment by Pylogmon** [comment]
gnome无法获取焦点，也不知道是gnome的问题还是tauri的问题，目前来看deepin和kde体验都还不错

**Comment by Pylogmon** [comment]
这种事情群里讨论就行，没必要提个issue
