### ISSUE TITLE
[Feature]: openAI無法翻譯某些"不適當內容"

### ISSUE THREAD

**Issue by kof11** [Pylogmon/pot#63]
### 需求描述

![](https://images2.imgbox.com/5a/bc/IfZCJxbj_o.jpg)
我以為這是openAI自己的問題
但我改用OpenAI Translator卻發現，居然可以成功翻譯！
![](https://images2.imgbox.com/de/d5/POwOwihG_o.jpg)
請問為什麼會這樣呢？

範例文字
----
虐めたい？
幼なじみの彼が呟く言葉に少なからずの不安を覚えるのは沙良
虐めたいなら私でいいじゃん……とは言えない彼女はその言葉の真意を確かめる事も出来ず、
不運にも聞かれてしまったきれいでクールで厳しい「如月美雪」先生に
指導室に呼び出されてしまった幼なじみを目で追うだけであった……

不用意な発言でこってりと絞られ尽くした彼は、三輪樹
やさぐれ感満載で、友達付き合いはそれなりの、一人が好きな一匹狼。
他人にもさほど興味がなかったはずであったが……
鈍くさい子を見るとつい虐めたくなってしまう……
という自分を最近発見したようであった……

働くバイト先。
だらしなくだぼっとしたスウェットに身を包み、サンダル履きでのたのたとスローテンポにやって来る彼女は、
髪も無造作に束ねおよそ女らしさのかけらもなく
その上鈍くさく陳列物を倒したりといったドジッ娘満載の見るからにポンコツで。
そこまで鈍くさくなければ……自分の前でそんな状況になっていなければ……苛つきが興奮にすり替わり、
怯える彼女に迫り、毟り取り、強引にその肢体を貪り尽くしていく毎に増す嗜虐感に、理性は抗えなかった……

泣き叫ぶ彼女を強引に割り開き、ピタッと閉じた秘唇に無理やり捩じ込む若気の屹立。
遮る抵抗感を強引に抉り押し込み中出しを決め込む樹……彼のすべてが開放的になった瞬間であった……

### 应用场景

希望能翻譯更多

**Comment by Pylogmon** [comment]
他们应该有专门的优化，我去看看

**Comment by Pylogmon** [comment]
我这边测试是可以正常翻译的，你如果无法翻译的话可以试试自定义prompt，pot是可以自定义prompt的，为了节省token，默认的prompt设置的很简单，你可以自定义一个效果更好的prompt
以下是openai translator的prompt
You are a professional translation engine, please translate the text into a colloquial, professional, elegant and fluent content, without the style of machine translation. You must only translate the text content, never interpret it.

**Comment by Pylogmon** [comment]
如果问题解决了这个issue可以关了
